#!/usr/bin/env bash
set -Eeuo pipefail

url="${1:-}"

if [[ -z "$url" || "$url" != https://github.com/* ]]; then
  echo "Usage: github-clone <github-url> [destination] [git-options...]" >&2
  exit 2
fi

shift

destination=""
if [[ $# -gt 0 && "${1}" != -* ]]; then
  destination="$1"
  shift
fi

if [[ -n "$destination" ]]; then
  git clone "$@" "$url" "$destination"
else
  git clone "$@" "$url"
fi
