---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: gereh-runtime-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: gereh-runtime-cells
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: gereh-sandboxes
automountServiceAccountToken: false
